Added main page with car Ads
Pulatov-iOS/CarAdvertisements_Swift-Storyboard pull request #1
Opened 2023-12-12 12:13 UTC by Pulatov-iOS

Added to the application: 
1. tab bar with five windows;
2. table with ads in the main window;
3. custom cell with a car announcement;
4. buttons for search and parameters;
5. button to hide and add an ad to favorites.
![Снимок экрана 2023-12-12 в 13 46 22](https://github.com/Pulatov-iOS/CarAdvertisements_Swift-Storyboard/assets/71228565/67d9aefe-851b-4b06-870d-f7abab5d551b)
![Снимок экрана 2023-12-12 в 13 49 54](https://github.com/Pulatov-iOS/CarAdvertisements_Swift-Storyboard/assets/71228565/176ed77e-655b-4a8f-b720-c48efeb6d72f)
![Снимок экрана 2023-12-12 в 13 47 44](https://github.com/Pulatov-iOS/CarAdvertisements_Swift-Storyboard/assets/71228565/d15da62a-7c12-4973-9675-10b86ce73783)
![Снимок экрана 2023-12-12 в 13 48 15](https://github.com/Pulatov-iOS/CarAdvertisements_Swift-Storyboard/assets/71228565/af52ba81-f5ca-49bf-b06e-93a277d5b75b)

2023-12-13 21:07 UTC, mishamorochko requested changes
В целом все хорошо, нужно кое-что поправить и можно мержить

2023-12-13 21:07 UTC, mishamorochko commented on CarAdvertisements_Swift-Storyboard/Views/CarsAdsViewController.swift
> +    private var ads = [
Это лучше вынести в другое место, например в файл где находится эта моделька

2023-12-13 21:07 UTC, mishamorochko commented on CarAdvertisements_Swift-Storyboard/Views/CarsAdsViewController.swift
> +        carAdsTableView.register(UINib(nibName: "XibTableViewCell", bundle: nil), forCellReuseIdentifier: "XibTableViewCell")
Тут лучше навести порядок, сделать функциональную декомпозицию

2023-12-13 21:07 UTC, mishamorochko commented on CarAdvertisements_Swift-Storyboard/Views/ImageCollectionViewCell.swift
> +        case "first":
Завязываться на строки не лучшая идея, нужно этот момент переработать. Можно попробовать с enum

2023-12-20 10:30 UTC, Pulatov-iOS commented on CarAdvertisements_Swift-Storyboard/Views/ImageCollectionViewCell.swift
> +        case "first":
Не совсем если честно понял, что означает "попробовать с enum", это ведь и так же у нас enum. Или тут речь идет про enum в enum?

2023-12-24 12:48 UTC, mishamorochko approved these changes

2023-12-25 09:56 UTC, merged